import { useEffect, useState } from "react";
import { Sparkles, Users, CalendarDays, UserX } from "lucide-react";
import Layout from "../../components/Layout";
import api from "../../api/client";

export default function AdminDashboard() {
  const [briefing, setBriefing] = useState(null);
  const [loadingBriefing, setLoadingBriefing] = useState(true);

  useEffect(() => {
    api
      .get("/ai/pulse-briefing")
      .then((res) => setBriefing(res.data))
      .finally(() => setLoadingBriefing(false));
  }, []);

  return (
    <Layout>
      <h1 className="text-2xl font-bold text-slate-800">Admin Dashboard</h1>
      <p className="text-slate-500 mt-1">Today's HR overview, generated by AI from live data.</p>

      <div className="card mt-6 bg-gradient-to-br from-brand-600 to-brand-700 text-white border-none">
        <div className="flex items-center gap-2 mb-3">
          <Sparkles size={18} />
          <p className="font-semibold">AI Pulse Briefing</p>
        </div>
        {loadingBriefing ? (
          <p className="text-brand-100 text-sm">Generating today's briefing…</p>
        ) : (
          <p className="text-brand-50 leading-relaxed">{briefing?.briefing}</p>
        )}
      </div>

      {briefing?.stats && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6">
          <StatCard icon={Users} label="Total Employees" value={briefing.stats.totalEmployees} />
          <StatCard icon={CalendarDays} label="Pending Leave Requests" value={briefing.stats.pendingLeaves} />
          <StatCard icon={UserX} label="Absences Today" value={briefing.stats.todayAbsences} />
        </div>
      )}
    </Layout>
  );
}

function StatCard({ icon: Icon, label, value }) {
  return (
    <div className="card">
      <div className="w-10 h-10 rounded-xl bg-brand-50 flex items-center justify-center mb-3">
        <Icon size={20} className="text-brand-600" />
      </div>
      <p className="text-2xl font-bold text-slate-800">{value}</p>
      <p className="text-sm text-slate-500">{label}</p>
    </div>
  );
}
